let product = [{
        "food": "BA CHỈ RIM XÌ DẦU",
        "ingredient": ["300gr thịt heo", "Vài nhánh tỏi băm nhỏ", "1 nhánh gừng băm nhỏ", "1 ít dầu mè", "2 thìa xì dầu", "1 thìa đường", "1 chút nước mắm", "1 ít hành lá xắt nhỏ", "Gia vị: bột nêm, tiêu"],
        "how2cook": ["Thịt heo rửa sạch, thấm khô nước, thái miếng nhỏ vừa ăn.", "Cho thịt heo vào chảo xào sơ qua cho thịt ra bớt mỡ, nếu dùng thịt nạc bạn chỉ cần xào cho thịt không còn màu hồng là được.", "Cho tỏi băm, gừng băm vào thịt rồi xào cho thật thơm rồi mới cho xì dầu và các gia vị còn lại vào đảo đều cho thấm gia vị. Thêm chút nước rồi đậy vung cho thịt chín mềm, nước sốt rút cạn thì cho hành hoa vào là tắt bếp."],
        "FAT": "11",
        "PRO": "28",
        "CAR": "0",
        "FIB": "0",
        "short": "Hương vị Việt Nam<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị quen thuộc từ quê hương Việt Nam thân yêu đến bàn ăn của bạn<br>Ba chỉ tươi ngon rim cùng xì dầu tạo nên một món ăn khó quên."],
        "img": "../img/bachirimxidaublack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/bachirimxidau.jpg",
        "code": "HpIrNX0ts5Y"
    },
    {
        "food": "BÁNH MÌ HEO QUAY",
        "ingredient": ["Thịt ba chỉ (nên chọn phần nạc nhiều hơn phần mỡ để bánh đỡ bị ngấy)", "Bột ngũ vị hương", "Rượu trắng, giấm", "Hành, tỏi băm, ớt", "Nước cốt chanh", "Đường, mắm, muối", "Dưa leo và các loại rau sống."],
        "how2cook": ["Rửa sạch thịt heo, dùng tăm đâm những lỗ nhỏ trên thịt để nhanh ngấm gia vị.", "Cho thịt vào tô rồi cho rượu trắng, giấm, muối, bột nêm, nước mắm, ngũ vị hương rồi trộn đều để ướp thịt. Ướp trong khoảng 6 tiếng.", "Cho thịt heo vào chảo đã sôi dầu, để phần bì miếng thịt bên dưới chảo. Khi miếng bì giòn thì lật tiếp mặt khác cho đến khi chín đều thì tắt bếp.", "Vớt thịt ra cho ráo dầu rồi thái thịt thành miếng chỏ vừa ăn kẹp vào bánh mì."],
        "FAT": "19",
        "PRO": "11",
        "CAR": "20",
        "FIB": "2",
        "short": "Hương vị Việt Nam<br>Giá: 40,000 VND",
        "long": ["Đem đến hương vị quen thuộc từ quê hương Việt Nam thân yêu đến bàn ăn của bạn<br>Bánh mì giòn rụm ăn cùng thịt heo thơm phức béo ngậy sẵn sàng đi cùng bạn đến bất cứ nơi đâu."],
        "img": "../img/banhmiheoquayblack.jpg",
        "price": "40,000 VND",
        "priceNum": "40000",
        "link": "./img/banhmiheoquay.jpg",
        "code": "Y6B7-tNIqJc"
    },
    {
        "food": "CƠM BÒ BÍT TẾT",
        "ingredient": ["Thịt thăn bò 2 lát (mỗi lát 300gr)", "Nước tương", "Nước cốt Yuzu", "Shio Koji", " Hành khô", " Hành lá", "Dầu mè", "Gia vị thông dụng"],
        "how2cook": ["Pha nước sốt: Cho vào tô 4 muỗng cà phê nước tương, 3 uỗng nuóc cốt Yuzu, 3 muỗng Shio Koji, 3 muỗng đướng, 4 muỗng hành khô băm nhuyễn, ít hành lá rồi khuấy đều.", "Thịt bò mua về rửa sơ qua để ráo. Thoa đều lớp dầu mè lên 2 mặt thịt sau đó rắc ít muối vs ít tiêu lên khắp bề mặt thịt.", "Cho thịt vào áp chảo từ 1,5 - 2 phút.", "Cho thịt ra đĩa, tưới nước sốt lên để sốt ngấm vào thịt."],
        "FAT": "23",
        "PRO": "37",
        "CAR": "57",
        "FIB": "10",
        "short": "Hương vị Châu Âu<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị mới lạ từ Châu Âu đến bàn ăn của bạn<br>Cơm nóng hổi ăn cùng thịt bò bít tết thơm ngọt và nước sốt đậm đà sẽ không làm bạn thất vọng."],
        "img": "../img/combobittetblack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/combobittet.jpg",
        "code": "8xLdlZwyvBk"
    },
    {
        "food": "CƠM CHIÊN TÔM",
        "ingredient": ["Tôm 400 gr", "Cơm nguội 400 gr", "Hành lá 2 nhánh", "Hành tím 1 củ", "Ớt bột Hàn Quốc", "Tương ớt Hàn Quốc", " Trứng gà 1 quả", "Dầu ăn", "Muối", "Đường"],
        "how2cook": ["Tôm mua về cắt bỏ đầu, lột vỏ, sau đó rửa lại với nước nhiều lần rồi cắt thahf miếng nhỏ.", "Sơ chế nguyên liệu khác: Hành lá rửa sạch cắt nhỏ, hành tím lột vỏ cắt lát mỏng.", "Cho tôm vào chảo rồi thêm 1 muỗng canh ớt bột và 2 muỗng tương ớt đảo đều. Xào tôm với lửa vừa cho đến khi tôm săn lại thì cho hành vào đảo cùng.", "Cho cơm nguội vào tô, đập thêm 1 quả trứng vào rồi trộn đều. Cho cơm lên chảo đảo đều tay rồi co hỗn hợp tôm vào đảo cùng trong khoảng 5ph.", "Cho cơm ra đĩa rồi thưởng thức."],
        "FAT": "2",
        "PRO": "22",
        "CAR": "4",
        "FIB": "0",
        "short": "Hương vị Châu Á<br>Giá: 70,000 VND",
        "long": ["Đem đến hương vị tuy cũ mà mới từ Châu Á đến bàn ăn của bạn<br>Cơm chiên giòn tan ăn cùng tôm tươi sẽ đánh bại mọi người dùng khó tính nhất."],
        "img": "../img/comchientomblack.jpg",
        "price": "70,000 VND",
        "priceNum": "70000",
        "link": "./img/comchientom.jpg",
        "code": "JIMgW_l6xeM"
    },
    {
        "food": "CƠM CHIÊN TRỨNG",
        "ingredient": ["200g tôm tươi", "1 chén cơm chín", "2 quả trứng gà", "1 củ hành tây nhỏ", "60ml sữa tươi không đường", "Mayonnaise", "Xốt cà chua", "Muối, đường, nước tương, dầu ăn, hạt tiêu"],
        "how2cook": ["Bạn đem hành tây bóc vỏ, cắt nhỏ. Tiếp theo, đem tôm bóc vỏ, cắt nhỏ. Sau đó, ướp tôm với hành tây và ít muối với hạt tiêu xay.", "Bạn cho trứng ra tô, cho vào đó sữa tươi và xốt Mayonnaise rồi khuấy đều.", "Bạn cho chảo lên bếp, cho dầu ăn vào, rồi cho hỗn hợp trứng vào chiên vàng.", "Bạn cho nước tương với xốt cà chua cùng đường vào chén và khuấy đều.", "Cho dầu ăn vào chảo, khi dầu nóng, cho hỗn hợp tôm vào xào sơ. Khi tôm hơi đỏ, bạn cho cơm vào rồi rưới nước xốt lên và đảo đều tay cho cơm thấm đều nước xốt. Khi cơm tơi, bạn đặt trứng lên trên là thưởng thức được rồi đấy."],
        "FAT": "17",
        "PRO": "12",
        "CAR": "53",
        "FIB": "2",
        "short": "Hương vị Nhật Bản<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị của đất nước mặt trời mọc đến bàn ăn của bạn<br>Cơm nóng hổi ăn cùng trứng tạo nên hương vị đậm đà khó quên."],
        "img": "../img/comchientrungkieunhatblack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/comchientrungkieunhat.jpg",
        "code": "60nP4r0OeuI"
    },
    {
        "food": "CƠM GÀ XỐI MỠ",
        "ingredient": ["½ con gà chặt miếng.", "Dưa chuột, cà chua bi, mộc nhĩ.", "Tỏi, hành đầu trắng của hành, gừng.", "Hạt điều hoặc bột nghệ.", "Các loại gia vị: hạt nêm, đường, xì dầu, tương ớt, dấm ớt tỏi…"],
        "how2cook": ["Sơ chế nguyên liệu: Gà rửa sạch, chặt miếng vừa ăn. Ướp gà cùng với tỏi, hạt nêm, một chút đường trong khoảng 30 phút.", "Luộc gà: Bắc một nồi nước, trong đó cho đầu hành, gừng đập dập, thêm một chút muối rồi thả gà đã ướp vào luộc chín. Sau khi gà chín, vớt gà ra để khô thật ráo nước.", "Rán gà: Gà phải để thật khô thì khi rán để lớp da gà mới có thể giòn rụm. Đổ dầu vào chảo, để dầu thật nóng rồi thả gà vào rán cho tới khi lớp da giòn và ngả màu vàng cánh gián.", "Chiên cơm: Nước luộc gà lọc qua một tấm vải, dùng nước đó để nấu cơm. Trong lúc đó, phi thơm tỏi cùng với hạt điều, phi xong bỏ tỏi đi chỉ giữ lại phần mỡ chiên. Sau đó khi cơm chín, trộn đều cơm với phần mỡ ấy. Tiếp theo, bạn bắc chảo lên bếp, để lửa vừa và đảo đều tay phẩn cơm ấy cho đến khi hạt cơm săn lại và tắt bếp."],
        "FAT": "3",
        "PRO": "33",
        "CAR": "40",
        "FIB": "5",
        "short": "Hương vị Việt Nam<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị quen thuộc từ quê hương Việt Nam thân yêu đến bàn ăn của bạn<br>Cơm nóng hổi ăn cùng gà tươi xối mỡ là sự lựa chọn hợp lí cho một bữa ăn đầy đủ dưỡng chất."],
        "img": "../img/comgaxoimoblack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/comgaxoimo.jpg",
        "code": "XGYKQhFHZKo"
    },
    {
        "food": "ĐÙI GÀ RÔ TI",
        "ingredient": ["Đùi gà", "1 quả dừa tươi", "1 củ hành khô", "Vài nhánh tỏi", "2 thìa mật ong", "1 thìa rượu trắng", "1 thìa nước tương", "Muối, bột nêm, tiêu", "Dầu ăn"],
        "how2cook": ["Đùi gà đem bóp kỹ với 1 chút muối rồi rửa lại cho thật sạch, để cho ráo nước hoặc thấm khô sau đó dùng dao khứa vài đường trên đùi gà cho dễ thấm gia vị hơn. Hành khô và tỏi đem băm nhuyễn.", "Cho đùi gà vào tô cùng với chút muối, nước tương, bột nêm, tiêu, hành tỏi băm và trộn đều, ướp thịt ít nhất 30 phút hoặc để trong ngăn mát tủ lạnh qua đêm thịt sẽ ngấm gia vị ngon hơn.", "Đặt chảo lên bếp cùng với chút dầu ăn, khi dầu nóng bạn cho đùi gà vào chiên tới khi xém vàng 2 mặt.", "Đổ nước dừa tươi sâm sấp đùi gà rồi cho mật ong và đậy vung đun lửa nhỏ vừa tới khi nước sốt hơi sệt lại, nêm nếm sao cho vừa miệng hơi mặn mặn ngọt ngọt là tắt bếp."],
        "FAT": "20",
        "PRO": "21",
        "CAR": "21",
        "FIB": "1",
        "short": "Hương vị Châu Á<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị tuy cũ mà mới từ Châu Á đến bàn ăn của bạn<br>Đùi gà rô ti chưa làm bất cứ thực khách nào thất vọng."],
        "img": "../img/duigarotiblack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/duigaroti.jpg",
        "code": "IL0fCc4fDb0"
    },
    {
        "food": "GÀ CHIÊN SỐT TRỨNG MUỐI",
        "ingredient": ["Cánh gà 500 gr", "Bột chiên giòn 1 chén", "Bơ lạt 30 gr", "Lòng đỏ trứng muối 8 quả", "Tỏi 1 củ", "Gia vị 20 gr"],
        "how2cook": ["Ướp cánh gà: Cánh gà rửa sạch để ráo sau đó cho vào tô trộn đều với 1 muỗng cà phê tiêu đen và 1 chén bột chiên.", "Chiên cánh gà: Cho cánh gà vào chảo, chiên vàng 2 mặt rồi vớt ra để ráo dầu.", "Làm sốt trứng muối: Trứng muối rửa qua rượu rồi rửa qua nước sạch để ráo, sau đó cho vào tô nghiền nhỏ. Bắc chảo lên bếp, thêm 30gr bơ lạt, 5 tép tỏi băm phi thơm, trứng muối, 1 muỗng đường, 1 muỗng hạt nêm, rồi cho cánh gà vào đảo đều.", "Tắt bếp, dọn ra đĩa và thưởng thức."],
        "FAT": "4",
        "PRO": "30",
        "CAR": "20",
        "FIB": "3",
        "short": "Hương vị Châu Á<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị tuy cũ mà mới từ Châu Á đến bàn ăn của bạn<br>Gà chiên sốt trứng muối là đồ ăn không thể thiếu cho mọi cuộc vui của bạn và người thân."],
        "img": "../img/gachiensottrungmuoiblack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/gachiensottrungmuoi.jpg",
        "code": "cbdub3zft58"
    },
    {
        "food": "MÌ XÀO BÒ",
        "ingredient": ["4 gói mì tôm", "300 gr thịt bò", "1 bó rau cải thìa", "1 củ cà rốt", "Hành tím, tỏi, rau thơm", "Gia vị khác"],
        "how2cook": ["Sơ chế nguyên liệu: Thịt bò rửa sạch, thái mỏng ướp gia vị, dầu ăn, hành tỏi, để trong 15ph cho ngấm. Mì trần qua nc sôi, để ráo nước. Rau cải rửa sạch, cắt khúc. Cà rốt gọt vỏ, rửa sạch, cắt khúc.", "Bắc chảo lên bếp, phi thơm hành tỏi băm, cho thịt vào đảo chín tái thì trút ra đĩa.", "Xào cà rốt và rau cải trên lửa lớn rồi trút ra đĩa riêng.", "Cho mì vào xào cũng tỏi băm phi thơm và chút gia vị, đảo vài phút cho mì săn lại và ngấm gia vị.", "Cho thịt bò cùng rau củ vào đảo đều, nêm nếm lại gia vị cho vừa ăn."],
        "FAT": "9",
        "PRO": "11",
        "CAR": "16",
        "FIB": "1",
        "short": "Hương vị Châu Âu<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị mới lạ từ Châu Âu đến bàn ăn của bạn<br>Mì xào dai dai ăn cùng bò mềm và nước sốt đậm đà tạo nên một món ăn đi vào lòng người."],
        "img": "../img/mixaoboblack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/mixaobo.jpg",
        "code": "3C_Q7RGyYMs"
    },
    {
        "food": "MỰC DỒN THỊT",
        "ingredient": ["3 con mực ống loại vừa", "200g thịt lợn xay nhuyễn", "1 nắm miến khô, mộc nhĩ", "1 quả trứng gà", "¼ củ hành tây", "Hành khô, hành lá, ngò, tỏi, ớt", "Gia vị: tiêu, hạt nêm, đường, mì chính, giấm"],
        "how2cook": ["Sơ chế nguyên liệu: Mực tươi rửa sạch, tách râu mực và băm nhuyễn làm nhân, thân mực để ráo nước. Miién khô với mộc nhĩ ngâm nước nóng cho mềm rồi băm nhỏ. Nguyên liệu khác rửa sạch băm nhỏ.", "Trộn nhận: Cho tất cả nguyên liệu trên vào 1 cái tô lớn. Trộn đều các nguyên liệu với ít gia vị. Ướp nhân trong 15-20ph.", "Nhồi hộc hợp vào thân mực: Khi nhân thấm gia vị, nhồi nhân vào thân mực. Dùng tăm tre ghim chắc đầu mực sau khi mực được nhồi căng vừa phải.", "Hấp mực và hoàn thành: Cho mực vào nồi hấp cách thủy 20-25ph. Sau khi chín thì lấy mực ra để nguội 5ph. Cắt mực thành khoanh tròn để hoàn thành món ăn."],
        "FAT": "2",
        "PRO": "16",
        "CAR": "4",
        "FIB": "0",
        "short": "Hương vị Châu Á<br>Giá: 70,000 VND",
        "long": ["Đem đến hương vị tuy cũ mà mới từ Châu Á đến bàn ăn của bạn<br>Mực dồn thịt chưa bao giờ vắng mặt trong các cuộc vui của bạn và đồng nghiệp."],
        "img": "../img/mucdonthitblack.jpg",
        "price": "70,000 VND",
        "priceNum": "70000",
        "link": "./img/mucdonthit.jpg",
        "code": "LHc6nk0hVEs"
    },
    {
        "food": "NUI XÀO BÒ",
        "ingredient": ["Thịt bò: 200g", "Nui: 150g", "Cải ngọt: 130g", "Hành tây: 1 củ", "Hành tím, tỏi: 2 củ", "Cà rốt: 1 củ", "Ớt sừng: 1 quả", "Gia vị: đường, hạt nêm, muối, tương cà, nước tương, dầu ăn, dầu hào, tiêu."],
        "how2cook": ["Ướp thịt bò bằm khoảng 15 phút với các gia vị cho thấm, thêm 1 ít hành tỏi băm nhuyễn cho dậy mùi thơm", "Trong lúc chờ thịt bò ướp bạn tiến hành sơ chế các nguyên liệu. Cà rốt gọt vỏ, rửa sạch cắt mỏng. Ớt sừng chẻ dọc, bỏ hạt, cắt sợi. Hành tây cắt múi cau, hành tím và tỏi lột vỏ sau đó băm nhuyễn", "Ngâm nui với nước lạnh 20 phút cho nui mềm rồi đem luộc. Các bạn nấu nước sôi trước, đợi nước sôi, cho nui vào, nhớ cho thêm nửa muỗng muối và 2 muỗng dầu ăn vào để nui không bị dính lại với nhau nha. Luộc nui khoảng 10 phút, sau đó vớt ra để cho ráo nước", "Cho 1 ít dầu ăn vào chảo, đợi dầu sôi, cho hành tỏi băm nhuyễn vào phi thơm. Cho phần thịt bò bằm vào đảo đều, khi thịt bò vừa chín tới cho cà rốt, hành tây, cải, ớt và nui vào đảo đều tay", "Nêm thêm 1 ít tiêu và hạt nêm vào chảo, các bạn có thể thêm gia vị tùy theo sở thích của bản thân và gia đình. Tầm 3 phút sau tắt bếp là bạn đã có ngay món nui xào thịt bò bằm vô cùng thơm ngon rồi"],
        "FAT": "26",
        "PRO": "14",
        "CAR": "21",
        "FIB": "4",
        "short": "Hương vị Châu Âu<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị mới lạ từ Châu Âu đến bàn ăn của bạn<br>Nui xào dai dai ăn cùng bò mềm và nước sốt đậm đà tạo nên một món ăn đi vào lòng người."],
        "img": "../img/nuixaoboblack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/nuixaobo.jpg",
        "code": "HBW08JKHc2M"
    },
    {
        "food": "THỊT KHO TIÊU",
        "ingredient": ["500g thịt ba chỉ", " Hành lá, hành tím, tỏi, ớt, hạt tiêu xay", "Gia vị: muối, đường, nước mắm, dầu ăn…"],
        "how2cook": ["Sơ chế nguyên liệu: Thịt ba chỉ rửa sạch, cắt thành miếng vừa ăn. Hành tím, tỏi đem bóc vỏ, hành lá bỏ rễ rửa sạch và đập dập thái nhỏ.", "Ướp thịt: ½ thìa muối, 2 thìa nước mắm,½ thìa hạt tiêu, 1 thìa đường, 1 thìa ớt băm, 1 thìa tỏi băm, hành lá thái nhỏ. Ướp thịt cùng với hỗn hợp trên trong 15ph.", "Thắng nước màu kho thịt.", "Nấu thịt kho tiêu: Cho tỏi và hành băm vào phi thơm. Gắp thịt đã tẩm ướp vào trong nồi rồi đảo liên tục đến khi thịt săn lại thì cho nước hàng vào xâm xấp mặt thịt. Cho hành lá vào và đun tiếp với lửa vừa cho đến khi nước thịt kho cạn dần và sánh lại thì tắt bếp."],
        "FAT": "7",
        "PRO": "17",
        "CAR": "5",
        "FIB": "0",
        "short": "Hương vị Việt Nam<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị quen thuộc từ quê hương Việt Nam thân yêu đến bàn ăn của bạn<br>Thịt kho tiêu có làm bạn hoài niệm về những kỉ niệm xưa kia? Một món ăn làm khơi dậy lại mọi giác quan của bạn."],
        "img": "../img/thitkhotieublack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/thitkhotieu.jpg",
        "code": "mTGicMWtSSA"
    },
    {
        "food": "TÔM RIM THỊT",
        "ingredient": ["250g tôm tươi", "100g thịt ba chỉ", "Nước dừa", "Hành lá, tỏi băm, hành tím băm", "Gia vị: đường, tiêu, nước mắm…"],
        "how2cook": ["Sơ chế tôm thịt: Tôm cắt bỏ chân, đuôi tôm và phần đầu, rửa sạch để ráo. Thịt rửa sạch thái miếng vừa ăn. Ướp tôm và thịt với 1 chút hạt nêm, tiêu, nước mắm.", "Rim thịt ba chỉ, tôm với nước dừa: Phi thơm hành tỏi rồi cho tôm vào xào, tôm săn lại thì cho ra đĩa riêng. Cho thịt ba chỉ vào rang. Khi thịt cháy cạnh thì cho phần tôm đã xào vào đảo cùng.", "Pha hỗn hợp nước mắm, đường, bột ngọt rồi đổ vào chảo tôm thịt. Tiếp theo đổ thêm nước dừa.", "Rim tôm và thịt trên lửa nhỏ cho thấm gia vị đến khi nước cạn thì cho hành lá và chút tiêu vào là được."],
        "FAT": "9",
        "PRO": "13",
        "CAR": "19",
        "FIB": "2",
        "short": "Hương vị Châu Á<br>Giá: 70,000 VND",
        "long": ["Đem đến hương vị tuy cũ mà mới từ Châu Á đến bàn ăn của bạn<br>Một món ăn đầy đủ dưỡng chất cho một ngày làm việc hiệu quả chưa bao giờ thiếu vắng Tôm rim thịt, hãy thử ngay"],
        "img": "../img/tomrimthitblack.jpg",
        "price": "70,000 VND",
        "priceNum": "70000",
        "link": "./img/tomrimthit.jpg",
        "code": "NIhh-EQc7pU"
    },
    {
        "food": "TRỨNG CHIÊN TÔM",
        "ingredient": ["3 quả trứng gà", " 200gr tôm tươi", "2 tai nấm mèo", "1 thìa canh hành tím băm", "Nước mắm, tiêu xay", "Hạt nêm (tùy thích)", "2 cây hành lá"],
        "how2cook": ["Sơ chế chuyên liệu: Tôm lọt vỏ rửa sạch. Nấm mèo ngâm nở, rửa sạch băm nhỏ. Hành rửa sạch, thái nhỏ.", "Trộn chung tôm + nấm mèo + hành tím băm + tiêu xay + nước mắm + hạt nêm cho thật đều, sau đó đập trứng gà vào tôm và đánh cho tôm trứng hòa đều.", "Đặt chảo lên bếp với 5 thìa canh dầu ăn, đun nóng rồi cho hỗn hợp tôm trứng vào chảo và dàn đều, rải hành lên mặt rồi rán vàng mặt dưới. Khi mặt dưới vàng thì lật mặt trên xuống cho trứng chín đều."],
        "FAT": "14",
        "PRO": "6",
        "CAR": "30",
        "FIB": "3",
        "short": "Hương vị Châu Á<br>Giá: 70,000 VND",
        "long": ["Đem đến hương vị tuy cũ mà mới từ Châu Á đến bàn ăn của bạn<br>Một món ăn đầy đủ dưỡng chất cho một ngày làm việc hiệu quả chưa bao giờ thiếu vắng Trứng chiên tôm, hãy thử ngay"],
        "img": "../img/trungchientomblack.jpg",
        "price": "70,000 VND",
        "priceNum": "70000",
        "link": "./img/trungchientom.jpg",
        "code": "WO4zvQejTiw"
    },
    {
        "food": "XÍU MẠI SỐT CÀ CHUA",
        "ingredient": ["Thịt heo 300 gr", "Hành tây 1 củ, hành tím 2 củ, hành lá 3 cây", "Tỏi 2 củ", "Sắn 1 củ", "Trứng gà 1 quả", "Cà chua chín 4 quả, ớt 2 quả", "Ngò rí 50 gr", "Bánh mì 100 gr"],
        "how2cook": ["Trộn thịt: Cho thịt heo xay vào một cái tô lớn, đập trứng gà vào, cho thêm phần đầu hành, hành tây, hành tím, tỏi phi, củ sắn vắt ráo nước. Nêm vào 1 thìa cà phê hạt nêm, 1 thìa cà phê hạt tiêu, 1 thìa cà phê đường, 1 thìa cà phê muối, 2 thìa cà phê dầu mè.Bạn bóp nát bánh mì rồi cho hết vào tô, trộn đều tất cả nguyên liệu.Dùng bao tay trộn đều tất cả nguyên liệu. Ướp trong vòng 15 phút để thịt ngấm gia vị.", "Viên xíu mại: Sau 15 phút ướp thịt, bạn đeo bao tay, lấy một lượng thịt vừa đủ ra lòng bàn tay rồi vo thành các viên nhỏ vừa ăn.Để thịt không bị dính vào tay khi vo thịt, bạn thoa chút dầu ăn lên bao tay trước khi làm và thi thoảng thoa lại một chút. Làm lần lượt đến khi hết nguyên liệu.", "Hấp xíu mại: Cho viên xíu mại vào nồi hấp trong 15-20ph, sau đó cho ra đĩa, phần nước tiết ra để nấu sốt cà chua.", "Làm sốt cà chua: Băm nhỏ vài nhánh tỏi rồi cho vào chảo phi thơm. Cho phần hành tím và hành tây thái nhuyễn, cà chua thái hạt lựu vào xào, hạ lửa nhỏ, nấu đến khi cà chua mềm.", "Khi sốt cà chua sôi thì thả viên xíu mại vào, đảo nhẹ nhàng cho xíu mại thấm nước sốt thì tắt bếp."],
        "FAT": "4",
        "PRO": "12",
        "CAR": "3",
        "FIB": "1",
        "short": "Hương vị Châu Á<br>Giá: 50,000 VND",
        "long": ["Đem đến hương vị tuy cũ mà mới từ Châu Á đến bàn ăn của bạn<br>Xíu mại sốt cà chua sẽ luôn đồng hành cùng bữa ăn của bạn với sự đầy đủ từ hương vị đến các chất dinh dưỡng, hãy thử ngay"],
        "img": "../img/xiumaisotcachuablack.jpg",
        "price": "50,000 VND",
        "priceNum": "50000",
        "link": "./img/xiumaisotcachua.jpg",
        "code": "pHyI5TTJAkQ"
    }
];
let drink = [{
        "drink": "7 UP",
        "price": "15,000",
        "priceNum": "15000",
        "link": "./img/7up.jpg"
    },
    {
        "drink": "Coca-Cola",
        "price": "15,000",
        "priceNum": "15000",
        "link": "./img/coca.jpg"
    },
    {
        "drink": "Fanta",
        "price": "15,000",
        "priceNum": "15000",
        "link": "./img/fanta.jpg"
    },
    {
        "drink": "Milo",
        "price": "25,000",
        "priceNum": "25000",
        "link": "./img/milo.jpg"
    },
    {
        "drink": "Trà chanh",
        "price": "15,000",
        "priceNum": "15000",
        "link": "./img/nestea.jpg"
    }
];